name: Check

on:
  push:
    branches: [master, develop]
  pull_request_review:
    types: [submitted]

jobs:
  check:
    name: Prettier and unit testing check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run prettier-check
    - run: npm test