name: Build and Deploy Storybook
on: workflow_dispatch

jobs:
  deploy:
    name: Build and Deploy Storybook
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: yarn install --frozen-lockfile
    - run: yarn build-storybook

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: docs-build
        CLEAN: true
        TARGET_FOLDER: docs
