name: Deploy

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy package to NPM
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
