name: Deploy Next Dry Run

on: [workflow_dispatch]

jobs:
  deploy:
    name: Deploy package to NPM
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: next
        check-version: false
        dry-run: true
